/**
 * @file main.c
 * @brief This file contains the main function of the project
 * @author Modular-MX
 * 
 * ***********************************************************************************************************************
 * Example 1. 
 * The example below sets the FlexCAN2 in classic mode plus interrupt. Pins 81 and 80 configured as CAN Tx and Rx. 
 * The example below only transmits one single 8 bytes message every 5 seconds at 100Kpbs. The difference with previous 
 * example is that we are using the CanIf layer configured for one single Id message, one single buffer is used for 
 * one single Hoh object. Notice that now we use function CanIf_Transmit to send the message, in case we need a notification 
 * to signal when the message is transmitted we need to define CDD_UserTxConfirmation function as we previously did in Tresos. 
 * CanIf->CanIfTxPduCfg->CanIfTxPduCfg->CanIfTxPduUserTxConfirmationName: "CDD_UserTxConfirmation". 
 * ***********************************************************************************************************************
*/

/*
 * IMPORTANT:
 * In 'Build\cfg\src\CanIf_Cfg.c' we need to initialize the Can_43_FLEXCAN_Driver_P2Func with the rest of the functions. 
 * The only down side is that this file is auto generated by the Tresos tool and any manual modification you perform 
 * will erase every time is generated again.
 * 
 * static const CanIf_CanDrvFuncPtrType Can_43_FLEXCAN_Driver_P2Func = 
 * {
 *     &Can_43_FLEXCAN_Write,
 *     &Can_43_FLEXCAN_SetControllerMode   <-- ADD this in line 89 of 'Build\cfg\src\CanIf_Cfg.c'
 * };
*/

#include "Mcu.h"
#include "Port.h"
#include "Platform.h"
#include "Osif.h"
#include "Can_43_FLEXCAN.h"
#include "CanIf.h"

/*flags to indicate Transmition*/
boolean CanIf_bTxFlag = FALSE;
/*message to Tx and Rx*/
uint8 Can_au8Sdu8bytes[8U] = {0x01U, 0x02U, 0x03U, 0x04U, 0x05U, 0x06U, 0x11U, 0x12U};

void EcuM_Init( void );

/*this is dummy delay function prepare just for this example, in a real application 
no delay shall be used*/
void Delay( uint32 ms )
{
    uint32 Timeout = OsIf_MicrosToTicks( ms * 1000u, OSIF_COUNTER_SYSTEM );
    uint32 SeedTick = OsIf_GetCounter( OSIF_COUNTER_SYSTEM );
    uint32 ElapsedTime = 0u;
    do
    {
        ElapsedTime += OsIf_GetElapsed( &SeedTick, OSIF_COUNTER_SYSTEM );
    }while( ElapsedTime < Timeout );
}

/*Callback function to indicate that the message was transmitted. The reference
to function shall be defined in file Autosar/CanIf/CanIf_Cdd.h, such file
must be created manualy*/
void CDD_UserTxConfirmation( PduIdType TxPduId, Std_ReturnType result )
{
    (void)TxPduId;
    if( result == E_OK )
    {
        CanIf_bTxFlag = TRUE;
    }
}

/**
 * @brief This is the main function of the project
 * 
 * This is the main function of the project, it is the entry point of the program
 * 
 * @return Always zero
*/
int main( void )
{
    PduInfoType PduInfo;

    EcuM_Init();

    /*Start the CAN controller and make it active in the CAN bus network*/
    Can_43_FLEXCAN_SetControllerMode( CanController_0, CAN_CS_STARTED );

    /*set the information to transmit*/
    PduInfo.SduDataPtr = Can_au8Sdu8bytes;
    PduInfo.SduLength = 8u;
    PduInfo.MetaDataPtr = NULL_PTR;

    while( 1u )
    {
        /*set the FlexCAN peripheral to transmit the message, the message will be
        transmitted by the CAN interrupt, this function will call the low level
        Can_43_FLEXCAN_Write with the low level data according de PDU configured*/
        CanIf_Transmit( CanIfTxPduCfg_0, &PduInfo );

        /*wait until the CAN interrupt transmit message, waiting is not the
        suitable way, but good enough for ilustration purposes, flag is 
        updated by the callback function CanIf_TxConfirmation*/
        while( CanIf_bTxFlag == FALSE );
        /*Clear the Tx flag*/
        CanIf_bTxFlag = FALSE;

        /*increase some values jus for ilustration purpose*/
        Can_au8Sdu8bytes[0]++;
        Can_au8Sdu8bytes[7]++;

        Delay( 5000u );
    }

    return 0u;
}

/**
 * @brief This function initialize the microcontroller and the peripherals
 * 
 * it is just a temporary function, in the future this function will be replaced when the EcuM module 
 * is configured and implemented
*/
void EcuM_Init( void )
{
    /*Init Mcu module, including internal PLL, reference to Mcu Config structure can 
    be found at Mcu_PBcfg.h and PLL defines at Mcu_Cfg.h*/
    Mcu_Init( &Mcu_Config );
    Mcu_InitClock( McuClockSettingConfig_0 );
    Mcu_SetMode( McuModeSettingConf_0 );
    /*Init the internal tick reference Systick Timer*/
    OsIf_Init( NULL_PTR );
    /*enable and setup interrupts in use by the Can Driver*/
    Platform_Init( NULL_PTR );

    /*Apply all the Pin Port microcontroller configuration*/
    Port_Init( &Port_Config );

    /*init the FlexCAN2 with the paramters set in Tresos WITHOUT loop back mode*/
    Can_43_FLEXCAN_Init( &Can_43_FLEXCAN_Config );
    CanIf_Init( &CanIf_Config );
}
